apiVersion: split.smi-spec.io/v1alpha3
kind: TrafficSplit
metadata:
  name: deploy-traffic-split
  namespace: default
spec:
  service: deploy1-service  # This is the service where traffic is split from
  backends:
    - service: frontend-service
      weight: 80   # 80% of traffic to deploy1-service
    - service: frontend0-service
      weight: 20   # 20% of traffic to deploy2-service
